export const invoices = [
  {
    invoice: "INV001",
    paymentStatus: "Paid",
    totalAmount: "$250.00",
    paymentMethod: "Credit Csadfasdfasdfasdfard",
    test1: "Pass",
    test2: "OK",
    Demotesting: "Check",
  },
  {
    invoice: "INV001",
    paymentStatus: "Paid",
    totalAmount: "$250.00",
    paymentMethod: "Credit Csadfasdfasdfasdfard",
    test1: "Pass",
    test2: "OK",
    Demotesting: "Check",
  },
  {
    invoice: "INV001",
    paymentStatus: "Paid",
    totalAmount: "$250.00",
    paymentMethod: "Credit Csadfasdfasdfasdfard",
    test1: "Pass",
    test2: "OK",
    Demotesting: "Check",
  },
  {
    invoice: "INV001",
    paymentStatus: "Paid",
    totalAmount: "$250.00",
    paymentMethod: "Credit Csadfasdfasdfasdfard",
    test1: "Pass",
    test2: "OK",
    Demotesting: "Check",
  },
  {
    invoice: "INV001",
    paymentStatus: "Paid",
    totalAmount: "$250.00",
    paymentMethod: "Credit Csadfasdfasdfasdfard",
    test1: "Pass",
    test2: "OK",
    Demotesting: "Check",
  },
  {
    invoice: "INV001",
    paymentStatus: "Paid",
    totalAmount: "$250.00",
    paymentMethod: "Credit Csadfasdfasdfasdfard",
    test1: "Pass",
    test2: "OK",
    Demotesting: "Check",
  },

  {
    invoice: "INV001",
    paymentStatus: "Paid",
    totalAmount: "$250.00",
    paymentMethod: "Credit Csadfasdfasdfasdfard",
    test1: "Pass",
    test2: "OK",
    Demotesting: "Check",
  },
  {
    invoice: "INV001",
    paymentStatus: "Paid",
    totalAmount: "$250.00",
    paymentMethod: "Credit Csadfasdfasdfasdfard",
    test1: "Pass",
    test2: "OK",
    Demotesting: "Check",
  },{
    invoice: "INV001",
    paymentStatus: "Paid",
    totalAmount: "$250.00",
    paymentMethod: "Credit Csadfasdfasdfasdfard",
    test1: "Pass",
    test2: "OK",
    Demotesting: "Check",
  },
  
];

export const gradeComposition = [
  {
    id: "oie112",
    name: "Midterm",
    scale: "30",
  },
  {
    id: "asd1232",
    name: "Exercises1",
    scale: "5",
  },
  {
    id: "fas1241",
    name: "Finalterm",
    scale: "50",
  },
  {
    id: "sdf1231",
    name: "Exercises2",
    scale: "5",
  },
  {
    id: "fgw1421",
    name: "Exercises3",
    scale: "2",
  },
  {
    id: "fad1235",
    name: "Exercises5",
    scale: "2",
  },
  {
    id: "asg0693",
    name: "Exercises4",
    scale: "2",
  },
];